title:              Parth Soni
email:              parth.soni78738@gmail.com
description:        Senior Data Engineer â€” portfolio & blog
author:             Parth Soni
baseurl:            "" 
url:                "https://theparthsoni.github.io"

# Social Profiles
twitter_username:   soniparth_
github_username:    theparthsoni
facebook_username:  theparthsoni
instagram_username: soni.parth_
youtube_username:   soniparth
linkedin_username:  parthasoni

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-562N4ZF8X5 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
